### ISSUE TITLE
Issue when providing a custom config and using response: true

### ISSUE THREAD

**Issue by ream88** [fewlinesco/bamboo_smtp#142]
Thanks to https://github.com/fewlinesco/bamboo_smtp/pull/122 we can now provide a `response: true` flag when sending an email, however when using this flag in combination with a `config:` map, the whole thing errors:

```elixir
config = %{server: "..."}
BambooTrial.Mailer.deliver_now(BambooTrial.Email.test_email(), config: config, response: true)
```

errors with:

```
** (ArgumentError) The following settings have not been found in your settings:

* Key port is required for SMTP Adapter
* Key server is required for SMTP Adapter

They are required to make the SMTP adapter work. Here you configuration:

%{adapter: Bamboo.SMTPAdapter}

    (bamboo_smtp 2.1.0) lib/bamboo/adapters/smtp_adapter.ex:342: Bamboo.SMTPAdapter.raise_on_missing_configuration/2
    (bamboo_smtp 2.1.0) lib/bamboo/adapters/smtp_adapter.ex:84: Bamboo.SMTPAdapter.handle_config/1
    (bamboo 1.5.0) lib/bamboo/mailer.ex:292: Bamboo.Mailer.handle_adapter_config/1
```

**Comment by ream88** [comment]
Ok, this is an issue in bamboo itself, I will close this issue once the bamboo issue is closed! 😊
