### ISSUE TITLE
function :crypto.hmac/3 is undefined or private

### ISSUE THREAD

**Issue by masoudgs** [fewlinesco/bamboo_smtp#194]
Im getting following `function :crypto.hmac/3 is undefined or private` error when using smtp provider. any idea?

#### Logs:

```json
{
  "timestamp": "2021-06-18T16:54:59.000259Z",
  "message": "Task #PID<0.713.0> started from #PID<0.712.0> terminating\n** (UndefinedFunctionError) function :crypto.hmac/3 is undefined or private\n    (crypto 5.0.2) :crypto.hmac(:md5, \"PASSWORD\", \"<123456.123456@smtp.mailtrap.io>\")\n    (gen_smtp 0.15.0) /Users/dull/w/app/deps/gen_smtp/src/smtp_util.erl:73: :smtp_util.compute_cram_digest/2\n    (gen_smtp 0.15.0) /Users/dull/w/app/deps/gen_smtp/src/gen_smtp_client.erl:489: :gen_smtp_client.do_AUTH_each/5\n    (gen_smtp 0.15.0) /Users/dull/w/app/deps/gen_smtp/src/gen_smtp_client.erl:452: :gen_smtp_client.try_AUTH/3\n    (gen_smtp 0.15.0) /Users/dull/w/app/deps/gen_smtp/src/gen_smtp_client.erl:335: :gen_smtp_client.open_smtp_session/2\n    (gen_smtp 0.15.0) /Users/dull/w/app/deps/gen_smtp/src/gen_smtp_client.erl:271: :gen_smtp_client.try_smtp_sessions/3\n    (gen_smtp 0.15.0) /Users/dull/w/app/deps/gen_smtp/src/gen_smtp_client.erl:258: :gen_smtp_client.send_it/2\n    (bamboo_smtp 3.0.0) lib/bamboo/adapters/smtp_adapter.ex:77: Bamboo.SMTPAdapter.deliver/2\n    (elixir 1.12.1) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2\n    (stdlib 3.15.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3\nFunction: #Function<0.98274997/0 in Bamboo.TaskSupervisorStrategy.deliver_later/3>\n    Args: []",
  "level": "error"
}
```

#### config.exs

```ex
config :app, App.Utils.Mailer,
  adapter: Bamboo.SMTPAdapter,
  server: "smtp.mailtrap.io",
  hostname: "smtp.mailtrap.io",
  port: 587,
  username: {:system, "MAILTRAP_USER"},
  password: {:system, "MAILTRAP_PASSWORD"},
  ssl: false,
  tls: :always
```

**Comment by tcitworld** [comment]
A wrapper for the `:crypto.hmac/3` depreciation [has been in `gen_smtp`](https://github.com/gen-smtp/gen_smtp/issues/207) for a while, what's your `gen_smtp` version?

**Comment by masoudgs** [comment]
@tcitworld I was using one of the old versions. I tried to manage the error by overriding package to the latest version for now. works well.

**Comment by tcitworld** [comment]
Latest `bamboo_smtp` should bring in `gen_smtp` 1.1.1, so maybe it's another dependency that you have an issue with?

**Comment by babariviere** [comment]
Hello, as said by @tcitworld, we are using `gen_smtp` version 1.1.1. Can you show us the dependencies you are using?

**Comment by masoudgs** [comment]
@tcitworld @babariviere Hmm, I don't think it's from another dependency and `mix deps.tree | grep smtp` shows im using `v3.0.0` which actually is old enough

```bash
$ mix deps.tree | grep smtp
├── bamboo_smtp ~> 3.0.0 (Hex package)
│   └── gen_smtp ~> 0.15.0 (Hex package)
```

**mix.exs**

```ex

  defp deps do
    [
      {:phoenix, "~> 1.5.1"},
      {:phoenix_pubsub, "~> 2.0"},
      {:phoenix_ecto, "~> 4.0"},
      {:ecto_sql, "~> 3.0"},
      {:postgrex, ">= 0.15.0"},
      {:phoenix_html, "~> 2.11"},
      {:jason, "~> 1.1", override: true},
      {:poison, "~> 3.1", override: true},
      {:plug_cowboy, "~> 2.1"},
      {:ecto_enum, ">= 1.4.0"},
      {:argon2_elixir, "~> 2.0.5"},
      {:ecto_soft_delete, "~> 1.0"},
      {:git_hooks, "~> 0.5.1", only: [:dev, :test], runtime: false},
      {:elixir_uuid, "~> 1.2"},
      {:tzdata, "~> 1.1", override: true},
      {:timex, "~> 3.0"},
      {:ex_json_schema, "~> 0.7.3"},
      {:ex_phone_number, "~> 0.2"},
      {:httpoison, "~> 1.7"},
      {:scrivener_ecto, "~> 2.0"},
      {:sonix, "~> 0.1.0"},
      {:decimal, "~> 1.8"},
      {:misc_random, "~> 0.2.9"},
      {:quantum, "~> 3.0"},
      {:secure_random, "~> 0.5.1"},
      {:bamboo_smtp, "~> 4.0.1"},
      {:bamboo, "~> 2.1.0"},
      {:hackney, "~> 1.9"},
      {:telemetry, "~> 0.4"},
      {:countries, "~> 1.6"},
      {:opentelemetry, "~> 0.6.0", override: true},
      {:opentelemetry_api, "~> 0.6.0", override: true},
      {:opentelemetry_exporter, "~> 0.6.0", override: true},
      {:opentelemetry_phoenix, "~> 0.2.0"},
      {:opentelemetry_ecto, "~> 1.0.0-rc.1", allow_pre: true}
    ]
  end
```

After upgrade bamboo and bamboo_smtp:

```bash
$ mix deps.tree | grep smtp
├── bamboo_smtp ~> 4.0.1 (Hex package)
│   └── gen_smtp ~> 1.1.1 (Hex package)
```

**Comment by babariviere** [comment]
In your mix.exs file, you are setting the version of bamboo to `2.1.0`, try upgrading it to `2.2.0` and tell me if it works

**Comment by babariviere** [comment]
@msudgh Does the error persist after upgrading bamboo_smtp?

**Comment by masoudgs** [comment]
@babariviere not anymore
