### ISSUE TITLE
Problem Encoding Comma in Filename

### ISSUE THREAD

**Issue by djthread** [fewlinesco/bamboo_smtp#219]
Hello!

We've encountered this error in our application.

>[error] Task #PID<0.31976.22> started from #PID<0.31952.22> terminating ** (ArgumentError) raise/1 and reraise/2 expect a module name, string or exception as the first argument, got: {:permanent_failure, '52.86.56.82', "554 Transaction failed: Expected ';', got \",\"\r\n"}     (bamboo 2.2.0) lib/bamboo/strategies/task_supervisor_strategy.ex:25: anonymous fn/3 in Bamboo.TaskSupervisorStrategy.deliver_later/3     (elixir 1.13.4) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2     (stdlib 4.0.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3 Function: #Function<0.41744430/0 in Bamboo.TaskSupervisorStrategy.deliver_later/3>     Args: []

We've circumvented the issue by avoiding having commas in our filenames, but I wanted to share this and see if there may be a better solution.

These same emails had worked fine in `3.1.3` but broke with our recent upgrade to `4.2.1`. Looking at the changelog, it would appear #183 is the most likely culprit for this breakage, but it's not clear exactly why or how.

Is there an opportunity here to improve bamboo_smtp?

And perhaps there is another issue indicated here as well where the bamboo package itself isn't throwing this error properly? It seems I may want to add a report with thoughtbot/bamboo about the second, wrapping issue here as well?

Thank you!!

**Comment by adamu** [comment]
> there is another issue indicated here as well where the bamboo package itself isn't throwing this error properly

This is a `bamboo_smtp` regression, which should be fixed by #216.
