### ISSUE TITLE
Bamboo.SMTPAdapter.rfc822_encode/1 error

### ISSUE THREAD

**Issue by joshuataylor** [fewlinesco/bamboo_smtp#59]
```
Process #PID<0.32722.14> terminating: {:function_clause, [{Base, :encode64, [nil, []], [file: 'lib/base.ex', line: 278]}, {Bamboo.SMTPAdapter, :rfc822_encode, 1, [file: 'lib/bamboo/adapters/smtp_adapter.ex', line: 149]}, {Bamboo.SMTPAdapter, :add_subject, 2, [file: 'lib/bamboo/adapters/smtp_adapter.ex', line: 145]}, {Bamboo.SMTPAdapter, :body, 1, [file: 'lib/bamboo/adapters/smtp_adapter.ex', line: 190]}, {Bamboo.SMTPAdapter, :to_gen_smtp_message, 1, [file: 'lib/bamboo/adapters/smtp_adapter.ex', line: 282]}, {Bamboo.SMTPAdapter, :deliver, 2, [file: 'lib/bamboo/adapters/smtp_adapter.ex', line: 61]}, {Task.Supervised, :do_apply, 2, [file: 'lib/task/supervised.ex', line: 85]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}
```

Backtrace
```
(bamboo_smtp) lib/bamboo/adapters/smtp_adapter.ex:149: Bamboo.SMTPAdapter.rfc822_encode/1
(bamboo_smtp) lib/bamboo/adapters/smtp_adapter.ex:145: Bamboo.SMTPAdapter.add_subject/2
(bamboo_smtp) lib/bamboo/adapters/smtp_adapter.ex:190: Bamboo.SMTPAdapter.body/1
(bamboo_smtp) lib/bamboo/adapters/smtp_adapter.ex:282: Bamboo.SMTPAdapter.to_gen_smtp_message/1
(bamboo_smtp) lib/bamboo/adapters/smtp_adapter.ex:61: Bamboo.SMTPAdapter.deliver/2
(elixir) lib/task/supervised.ex:85: Task.Supervised.do_apply/2
(stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

Mail still sends, this error doesn't show up every time, just sometimes.

**Comment by kdisneur** [comment]
Hi @joshuataylor,

The stacktrace seems to suggest the `subject` field is `nil`. Is it possible you send some emails with no subjects?

**Comment by joshuataylor** [comment]
@kdisneur apologies for not seeing this update. I might be, but it looks like the newest release fixes this anyway - awesome work! Will upgrade soon.

**Comment by kdisneur** [comment]
Yes it was just to be sure we tackle the right problem. But, anyway, we needed to fix this "no subject" issue.

Thanks for the bug report, hopefully this new release will fix your issue!
