### ISSUE TITLE
got error `{:missing_requirement, "smtp.my_site.com", :tls}`

### ISSUE THREAD

**Issue by Douvi** [fewlinesco/bamboo_smtp#72]
Here my configuration:

```
config :panda_phoenix, PandaPhoenix.Mailer,
  adapter: Bamboo.SMTPAdapter,
  server: "smtp.my_site.com",
  port: 465,
  username: "my_user_name",
  password: "my_password",
  auth: :always,
  tls: :always, # can be `:always` or `:if_available`
  allowed_tls_versions: [:"tlsv1", :"tlsv1.1", :"tlsv1.2"],
  ssl: true, # can be `true`
  retries: 4
```

Error:
```
[error] Task #PID<0.1099.0> started from #PID<0.1096.0> terminating
** (Bamboo.SMTPAdapter.SMTPError) There was a problem sending the email through SMTP.

The error is :retries_exceeded

More detail below:

{:missing_requirement, "smtp.my_site.com", :tls}

    (bamboo_smtp) lib/bamboo/adapters/smtp_adapter.ex:74: Bamboo.SMTPAdapter.handle_response/1
    (elixir) lib/task/supervised.ex:94: Task.Supervised.do_apply/2
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Function: #Function<0.115485522/0 in Bamboo.TaskSupervisorStrategy.deliver_later/3>
    Args: []
```

Can you help me, I do not know what I'm missing?

**Comment by kdisneur** [comment]
Hi @Douvi 

Are you sure your SMTP server supports TLS?

Looking at the [gen_smtp](https://github.com/Vagabond/gen_smtp/blob/e07022695735fe3b3eaf0fca52d85e91eef2a67f/src/gen_smtp_client.erl#L532...L534) code base, this exception seems to be raised when the server does not show `STARTTLS` as an available extension.

As a first test, could you try to set the `tls` option to `:if_available`?
